Examen Reclutamiento/Examen/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ClienteController;
use App\Http\Controllers\ProveedorController;
use App\Http\Controllers\SeguimientoController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

/*Route::get('/clientes', function () {
    return "aqui se devolvera clientes";
});*/

Route::resource('/clientes',ClienteController::class);
Route::resource('/proveedor',ProveedorController::class);
Route::resource('/seguimiento',SeguimientoController::class);

Route::get('sendemail',function(){

    $data= array(
        'name'=>"Se registro un nuevo envio"
    );
    Mail::send('mail.email',$data, function($message){
        $message->from('019030237@upq.edu.mx','Se registro un nuevo envio');

        $message->to('019030237@upq.edu.mx')->subject('test email');
    });
    return"Se envio un correo correctamente";
});

Examen Reclutamiento/Examen/resources/views/bd/clientes.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Guía de seguimiento</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{{asset('img/favicon.png')}}" rel="icon">
  <link href="{{asset('img/apple-touch-icon.png')}}" rel="apple-touch-icon">

  <!-- Vendor CSS Files -->
  <link href="{{asset('vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
  <link href="{{asset('vendor/bootstrap-icons/bootstrap-icons.css')}}" rel="stylesheet">
  <link href="{{asset('vendor/glightbox/css/glightbox.min.css')}}" rel="stylesheet">
  <link href="{{asset('vendor/swiper/swiper-bundle.min.css')}}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{{asset('css/style.css')}}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

</head>

<body>
    <div class="row">    
        <div id="contact" class="box-shadow-full">
            <div class="row">
                <a href="/"><button type="button" class="btn btn-primary btn-lg">Inicio</button></a>
                <div class="container">
                    <h4>Gestión de base de datos</h4>
                    <div class="row">
                        <div class="col-xl-12">
                        <form action="{{route('clientes.index')}}" method="get">
                                <div class="form-row">
                                    <div class="col-sm-4 my-1">
                                        <input type="text" class="form-control" name="texto">
                                    </div>
                                    <div class="col-auto mt-1">
                                        <input type="submit" class="btn btn-primary" value="Buscar">
                                    </div>
                                    <div class="col-auto mt-1">
                                        <a href="{{route('clientes.create')}}" class="btn btn-success">Nuevo</a>
                                    </div>
                                </div>
                        </form> 
                        </div>
                        <div class="col-xl-12">
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>Opciones</th>
                                            <th>Id Pedido</th>
                                            <th>Nombre</th>
                                            <th>Localización</th>
                                            <th>Tiempo en horas</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if(count($clientes)<=0)
                                            <tr>
                                                <td colspan="5">No hay resultados</td>
                                            </tr>
                                        @else
                                        @foreach ($clientes as $cliente)
                                            <tr>
                                            <td><a href="{{route('clientes.edit',$cliente->id_clientes)}}" class="btn btn-warning btn-sm">Editar </a> 

                                            
                                            </td>
                                            <td>{{$cliente->id_clientes}}</td>
                                            <td>{{$cliente->nombre}}</td>
                                            <td>{{$cliente->apellido}}</td>
                                            <td>{{$cliente->numero_celular}}</td>
                                            </tr>
                                            @include('bd.delete')
                                        @endforeach
                                        @endif
                                    </tbody>
                                </table>
                                {{$clientes->links()}}
                            </div> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>                
</html>

Examen Reclutamiento/Examen/resources/views/bd/createc.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear registro</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        <h4>Nuevo Registro</h4> 
        <div class="row">
            <div class="col-xl-12">
                <form action="{{route('clientes.store')}}" method="post">
                    @csrf
                    <div class="form-group">
                        <label for="id_clientes">Id pedido(1,2,3,....)</label>
                        <input type="text" class="form-control" name="id_clientes" required maxlength="11">
                    </div>
                    <div class="form-group">
                        <label for="nombre">Nombre</label>
                        <input type="text" class="form-control" name="nombre" required maxlength="50">
                    </div>
                    <div class="form-group">
                        <label for="apellido">Localización</label>
                        <input type="text" class="form-control" name="apellido" required maxlength="50">
                    </div>
                    <div class="form-group">
                        <label for="numero_celular">Tiempo en horas</label>
                        <input type="text" class="form-control" name="numero_celular" required maxlength="11">
                    </div>
                    <div class="class">
                        <input type="submit" class="btn btn-primary" value="Guardar">
                        <a href="javascript:history.back()">Ir al listado</a>
                    </div>
                </form>
            </div>
            
        </div>
    </div>
</body>
</html>

Examen Reclutamiento/Examen/resources/views/bd/cretatep.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear registro</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        <h4>Nuevo Proveedor</h4> 
        <div class="row">
            <div class="col-xl-12">
                <form action="{{route('proveedor.store')}}" method="post">
                    @csrf
                    <div class="form-group">
                        <label for="id_clientes">Id Proveedor(1,2,3,....)</label>
                        <input type="text" class="form-control" name="id_proveedor" required maxlength="11">
                    </div>
                    <div class="form-group">
                        <label for="nombre">Nombre</label>
                        <input type="text" class="form-control" name="nombre" required maxlength="50">
                    </div>
                    <div class="form-group">
                        <label for="apellido">Apellidos</label>
                        <input type="text" class="form-control" name="apellido" required maxlength="50">
                    </div>
                    <div class="form-group">
                        <label for="numero_celular">Numero Celular</label>
                        <input type="text" class="form-control" name="numero_celular" required maxlength="10">
                    </div>
                    <div class="class">
                        <input type="submit" class="btn btn-primary" value="Guardar">
                        <input type="reset" class="btn btn-default" value="Cancelar">
                        <a href="javascript:history.back()">Ir al listado</a>
                    </div>
                </form>
            </div>
            
        </div>
    </div>
</body>
</html>

Examen Reclutamiento/Examen/resources/views/bd/delete.blade.php
<!-- Modal -->
<div class="modal fade" id="modal-delete-{{$cliente->id_clientes}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
  <form action="{{route('clientes.destroy',$cliente->id_clientes)}}" method="post">
    @csrf
    @method('DELETE')              
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Eliminación</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Deseas eliminar al registro {{$cliente->nombre." ".$cliente->apellido}}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <input type="submit" class="btn btn-danger btn-sm" value="Eliminar">
      </div>
    </div>
    </form>
  </div>
</div>

Examen Reclutamiento/Examen/resources/views/bd/editc.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear registro</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        <h4>Actualizar CLiente</h4> 
        <div class="row">
            <div class="col-xl-12">
                <form action="{{route('clientes.update',$cliente->id_clientes)}}" method="post">
                    @csrf
                    @method ('PUT')
                    <div class="form-group">
                        <label for="id_clientes">Id Registro(1,2,3,....)</label>
                        <input type="text" class="form-control" name="id_clientes" required maxlength="11" value="{{$cliente->id_clientes}}">
                    </div>
                    <div class="form-group">
                        <label for="nombre">Nombre</label>
                        <input type="text" class="form-control" name="nombre" required maxlength="50" value="{{$cliente->nombre}}">
                    </div>
                    <div class="form-group">
                        <label for="apellido">Localización</label>
                        <input type="text" class="form-control" name="apellido" required maxlength="50" value="{{$cliente->apellido}}">
                    </div>
                    <div class="form-group">
                        <label for="numero_celular">Tiempo en horas</label>
                        <input type="text" class="form-control" name="numero_celular" required maxlength="11" value="{{$cliente->numero_celular}}">
                    </div>
                    <div class="class">
                        <input type="submit" class="btn btn-primary" value="Guardar">
                        <a href="javascript:history.back()">Ir al listado</a>
                    </div>
                </form>
            </div>
            
        </div>
    </div>
</body>
</html>

Examen Reclutamiento/Examen/resources/views/bd/editp.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear registro</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        <h4>Actualizar proveedor</h4> 
        <div class="row">
            <div class="col-xl-12">
                <form action="{{route('proveedor.update',$proveedor->id_proveedor)}}" method="post">
                    @csrf
                    @method ('PUT')
                    <div class="form-group">
                        <label for="id_proveedor">Id proveedor(1,2,3,....)</label>
                        <input type="text" class="form-control" name="id_proveedor" required maxlength="11" value="{{$proveedor->id_proveedor}}">
                    </div>
                    <div class="form-group">
                        <label for="nombre">Nombre</label>
                        <input type="text" class="form-control" name="nombre" required maxlength="50" value="{{$proveedor->nombre}}">
                    </div>
                    <div class="form-group">
                        <label for="apellido">Apellidos</label>
                        <input type="text" class="form-control" name="apellido" required maxlength="50" value="{{$proveedor->apellido}}">
                    </div>
                    <div class="form-group">
                        <label for="numero_celular">Numero Celular</label>
                        <input type="text" class="form-control" name="numero_celular" required maxlength="10" value="{{$proveddor->numero_celular}}">
                    </div>
                    <div class="class">
                        <input type="submit" class="btn btn-primary" value="Guardar">
                        <input type="reset" class="btn btn-default" value="Cancelar">
                        <a href="javascript:history.back()">Ir al listado</a>
                    </div>
                </form>
            </div>
            
        </div>
    </div>
</body>
</html>

Examen Reclutamiento/Examen/resources/views/bd/form.blade.php
<!DOCTYPE html>
<html>
 <head>
  <title>How Send an Email in Laravel</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

  <!-- Styles -->
  <style>
      html, body {
          background-color: #fff;
          color: #636b6f;
          font-family: 'Nunito', sans-serif;
          font-weight: 200;
          height: 100vh;
          margin: 0;
      }

      .full-height {
          height: 100vh;
      } 

      .content {
          text-align: center;
      }

      .title {
          font-size: 84px;
      } 
  </style>
 </head>
 <body>
  <br />
  <br />
  <br />
  <div class="container box" style="width: 970px;">
   <h1 style="text-align:center;"> <tutofox/> </h1>
   <h3 align="center">Cómo enviar un correo electrónico en Laravel</h3>
   <br/>
   @if (count($errors) > 0)
    <div class="alert alert-danger">
     <button type="button" class="close" data-dismiss="alert">×</button>
     <ul>
      @foreach ($errors->all() as $error)
       <li>{{ $error }}</li>
      @endforeach
     </ul>
    </div>
   @endif
   @if ($message = Session::get('success'))
   <div class="alert alert-success alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>
      <strong>{{ $message }}</strong>
   </div>
   @endif
   <form method="post" action="{{url('send')}}">
    {{ csrf_field() }}
    <div class="form-group">
     <label>Nombre</label>
     <input type="text" name="name" class="form-control" value="" />
    </div>
    <div class="form-group">
     <label> Email</label>
     <input type="text" name="email" class="form-control" value="" />
    </div>
    <div class="form-group">
     <label>Mensaje</label>
     <textarea name="message" class="form-control"></textarea>
    </div>
    <div class="form-group">
     <input type="submit" name="send" class="btn btn-info" value="Enviar" />
    </div>
   </form>

  </div>
 </body>
</html>

Examen Reclutamiento/Examen/resources/views/bd/proveedor.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Guía de seguimiento</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{{asset('img/favicon.png')}}" rel="icon">
  <link href="{{asset('img/apple-touch-icon.png')}}" rel="apple-touch-icon">

  <!-- Vendor CSS Files -->
  <link href="{{asset('vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
  <link href="{{asset('vendor/bootstrap-icons/bootstrap-icons.css')}}" rel="stylesheet">
  <link href="{{asset('vendor/glightbox/css/glightbox.min.css')}}" rel="stylesheet">
  <link href="{{asset('vendor/swiper/swiper-bundle.min.css')}}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{{asset('css/style.css')}}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

</head>

<body>
    <div class="row">    
        <div id="contact" class="box-shadow-full">
            <div class="row">
                <a href="/"><button type="button" class="btn btn-primary btn-lg">Inicio</button></a>
                <h4>Gestión de base de datos</h4>
                <div class="row">
                <div class="col-xl-12">
                        <form action="{{route('proveedor.index')}}" method="get">
                                <div class="form-row">
                                    <div class="col-sm-4 my-1">
                                        <input type="text" class="form-control" name="texto">
                                    </div>
                                    <div class="col-auto mt-1">
                                        <input type="submit" class="btn btn-primary" value="Buscar">
                                    </div>
                                    <div class="col-auto mt-1">
                                        <a href="{{route('proveedor.create')}}" class="btn btn-success">Nuevo</a>
                                    </div>
                                </div>
                        </form> 
                        </div>
                    <div class="col-lx-12">
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>Opciones</th>
                                        <th>Id proveedor</th>
                                        <th>Nombre</th>
                                        <th>Apellidos</th>
                                        <th>Numero Celular</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if(count($proveedor)<=0)
                                        <tr>
                                            <td colspan="5">No hay resultados</td>
                                        </tr>
                                    @else
                                    @foreach ($proveedor as $proveedores)
                                        <tr>
                                        <td><a href="{{route('proveedor.edit',$proveedor->id_proveedor)}}" class="btn btn-warning btn-sm">Editar </a> 
                                            <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modal-delete-{{$proveedor->id_proveedor}}">
                                                Eliminar
                                            </button></td>
                                        <td>{{$proveedores->id_proveedor}}</td>
                                        <td>{{$proveedores->nombre}}</td>
                                        <td>{{$proveedores->apellido}}</td>
                                        <td>{{$proveedores->numero_celular}}</td>
                                        </tr>
                                    @endforeach
                                    @endif
                                </tbody>
                            </table>
                        </div> 
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
                
              

Examen Reclutamiento/Examen/resources/views/bd/seguimiento.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Guía de seguimiento</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{{asset('img/favicon.png')}}" rel="icon">
  <link href="{{asset('img/apple-touch-icon.png')}}" rel="apple-touch-icon">

  <!-- Vendor CSS Files -->
  <link href="{{asset('vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
  <link href="{{asset('vendor/bootstrap-icons/bootstrap-icons.css')}}" rel="stylesheet">
  <link href="{{asset('vendor/glightbox/css/glightbox.min.css')}}" rel="stylesheet">
  <link href="{{asset('vendor/swiper/swiper-bundle.min.css')}}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{{asset('css/style.css')}}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

</head>

<body>
    <div class="row">    
        <div id="contact" class="box-shadow-full">
            <div class="row">
                <a href="/"><button type="button" class="btn btn-primary btn-lg">Inicio</button></a>
                <h4>Gestión de base de datos</h4>
                <div class="row">
                    <div class="col-lx-12">
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>Opciones</th>
                                        <th>Id seguimiento</th>
                                        <th>localizacion</th>
                                        <th>Tiempo</th>
                                        <th>Transportista</th>
                                        <th>cliente</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($seguimiento as $seguimientos)
                                        <tr>
                                        <td>Editar | Eliminar</td>
                                        <td>{{$seguimientos->id_seguimiento}}</td>
                                        <td>{{$seguimientos->localizacion}}</td>
                                        <td>{{$seguimientos->Tiempo}}</td>
                                        <td>{{$seguimientos->Transportista}}</td>
                                        <td>{{$seguimientos->cliente}}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div> 
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
                
              